jobs:
  changedfiles:
  - id: files
    uses: jitterbit/get-changed-files@v1
    with:
      format: 'json'
  - run: |
      readarray -t removed_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.removed }}')"
      for removed_file in ${removed_files[@]}; do
        echo "Do something with this ${removed_file}."
      done