name: output Changed files
on: 
  push:
    branches: [ main ]

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch changed files as json
      id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'
    - name: Print added modified
      run: |
        echo Added: ${{ steps.files.outputs.added_modified  }}
    - name: Print removed
      run: |
        echo Removed: ${{ steps.files.outputs.removed }}
    - name: Print renamed
      run: |
        echo renamed: ${{ steps.files.outputs.renamed }}

pushfile:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push