name: output Changed files
on: 
  push:
    branches: [ main ]

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch changed files as json
      id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'
    - name: Print added modified
      run: |
        echo Added: ${{ steps.files.outputs.added_modified  }}
    - name: Print removed
      run: |
        echo Removed: ${{ steps.files.outputs.removed }}
    - name: Print all
      run: |
        echo All: ${{ steps.files.outputs.all }}