name: Deploy Content to Azure Sentinel 2
on: 
  push:
    branches: [ main ]
    paths:
    - 'Detections/**.json'
    - '.github/workflows/sentinel-deploy**'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'newecotestrg2'
      workspaceName: 'cicd-test-la'
      directory: '${{ github.workspace }}/Detections'
      cloudEnv: 'AzurePPE'
      creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_2ab5d6cac2b84a81b9557a43b9f579d5 }}

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_2ab5d6cac2b84a81b9557a43b9f579d5 }}
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v1

    - name: Read deployment script
      id: deploymentScript
      uses: juliangruber/read-file-action@v1
      with:
        path: '${{ github.workspace }}/.github/workflows\azure-sentinel-deploy.ps1'
    
    - name: Deploy Analytic Rules
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ steps.deploymentScript.outputs.content }}
