  
name: Test 123
on: 
  push:
    branches: [ main ]

jobs:
  deploy-content:
    runs-on: windows-latest
    - name: Deploy Analytic Rules
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          Write-Output "[Warning] error happened"
