name: Test 123
on: 
  push:
    branches: [ main ]

jobs:
  test1:
    runs-on: windows-latest
    steps:
    - name: Test
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          Write-Output "[Warning] error happened"
